### ISSUE TITLE
this is satire, right?

### ISSUE THREAD

**Issue by relative** [0x44F/otax#4]
i was linked this and the only thing that comes to mind when looking at your github is that its satire

its satire, right?

**Comment by 0x44F** [comment]
Can you please stop overusing the word 'satire'. Proper term is "shitpost", its a shitpost. You've actually pissed me off now. I'm fuming. I'm a kettle ready to explode, and I'm coming for you pal. I don't think you understand what this means.

You see, I'm an Armed Assault 2 and 3 veteran. I served 9 years in the Australian Special Air Service Regiment and I'm going to use all my resources in order to eliminate you. You are my target, my fists are the bow and my words are the arrow. Good luck you mule.

**Comment by relative** [comment]
satire

**Comment by E4zily** [comment]
Satire.
